name = "CMU QPA Calculator"
main = "app/page.tsx"
compatibility_date = "2023-10-30"

workers_dev = true
route = { pattern = "cmu-qpa.pages.dev/*", zone_name = "pages.dev" }

[env.staging]
name = "cmu-qpa-staging"
route = { pattern = "cmu-qpa-staging.pages.dev/*", zone_name = "pages.dev" }

[site]
bucket = "./public"